/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.morgan.opnet.swig.activitynet;

public class activity_network {
  public static double getDBLMAX() {
    return activity_networkJNI.DBLMAX_get();
  }

  public static double getINTMAX() {
    return activity_networkJNI.INTMAX_get();
  }

  public static int arcLookup(SWIGTYPE_p_lemon__ListDigraph g, int startNodeId, int targetNodeId, SWIGTYPE_p_lemon__ListDigraph__Arc arc) {
    return activity_networkJNI.arcLookup(SWIGTYPE_p_lemon__ListDigraph.getCPtr(g), startNodeId, targetNodeId, SWIGTYPE_p_lemon__ListDigraph__Arc.getCPtr(arc));
  }

  public static int nodeLookup(SWIGTYPE_p_lemon__ListDigraph g, int nodeId, SWIGTYPE_p_lemon__ListDigraph__Node node) {
    return activity_networkJNI.nodeLookup(SWIGTYPE_p_lemon__ListDigraph.getCPtr(g), nodeId, SWIGTYPE_p_lemon__ListDigraph__Node.getCPtr(node));
  }

  public static void outputArcData(SWIGTYPE_p_lemon__ListDigraph g, SWIGTYPE_p_lemon__ListDigraph__ArcMapT_arcData_t aData, int fileId) {
    activity_networkJNI.outputArcData(SWIGTYPE_p_lemon__ListDigraph.getCPtr(g), SWIGTYPE_p_lemon__ListDigraph__ArcMapT_arcData_t.getCPtr(aData), fileId);
  }

  public static SWIGTYPE_p_std__string writeArcData(SWIGTYPE_p_lemon__ListDigraph g, SWIGTYPE_p_lemon__ListDigraph__ArcMapT_arcData_t aData) {
    return new SWIGTYPE_p_std__string(activity_networkJNI.writeArcData(SWIGTYPE_p_lemon__ListDigraph.getCPtr(g), SWIGTYPE_p_lemon__ListDigraph__ArcMapT_arcData_t.getCPtr(aData)), true);
  }

  public static void displayArcData(SWIGTYPE_p_lemon__ListDigraph g, SWIGTYPE_p_lemon__ListDigraph__ArcMapT_arcData_t aData) {
    activity_networkJNI.displayArcData__SWIG_0(SWIGTYPE_p_lemon__ListDigraph.getCPtr(g), SWIGTYPE_p_lemon__ListDigraph__ArcMapT_arcData_t.getCPtr(aData));
  }

  public static void displayArcData(SWIGTYPE_p_lemon__ListDigraph g, SWIGTYPE_p_lemon__ListDigraph__ArcMapT_lemon__ListDigraph__Arc_t label) {
    activity_networkJNI.displayArcData__SWIG_1(SWIGTYPE_p_lemon__ListDigraph.getCPtr(g), SWIGTYPE_p_lemon__ListDigraph__ArcMapT_lemon__ListDigraph__Arc_t.getCPtr(label));
  }

  public static void displayArcData(SWIGTYPE_p_lemon__ReverseDigraphT_lemon__ListDigraph_t g, SWIGTYPE_p_lemon__ListDigraph__ArcMapT_int_t label) {
    activity_networkJNI.displayArcData__SWIG_2(SWIGTYPE_p_lemon__ReverseDigraphT_lemon__ListDigraph_t.getCPtr(g), SWIGTYPE_p_lemon__ListDigraph__ArcMapT_int_t.getCPtr(label));
  }

  public static void displayArcData(SWIGTYPE_p_lemon__ListDigraph g, SWIGTYPE_p_lemon__ListDigraph__ArcMapT_int_t label) {
    activity_networkJNI.displayArcData__SWIG_3(SWIGTYPE_p_lemon__ListDigraph.getCPtr(g), SWIGTYPE_p_lemon__ListDigraph__ArcMapT_int_t.getCPtr(label));
  }

  public static void displayArcData(SWIGTYPE_p_lemon__ListDigraph g, SWIGTYPE_p_lemon__ListDigraph__ArcMapT_bool_t label) {
    activity_networkJNI.displayArcData__SWIG_4(SWIGTYPE_p_lemon__ListDigraph.getCPtr(g), SWIGTYPE_p_lemon__ListDigraph__ArcMapT_bool_t.getCPtr(label));
  }

  public static void displayArcData(SWIGTYPE_p_lemon__ListDigraph g, SWIGTYPE_p_lemon__ListDigraph__ArcMapT_double_t label) {
    activity_networkJNI.displayArcData__SWIG_5(SWIGTYPE_p_lemon__ListDigraph.getCPtr(g), SWIGTYPE_p_lemon__ListDigraph__ArcMapT_double_t.getCPtr(label));
  }

  public static SWIGTYPE_p_std__string writeNodeData(SWIGTYPE_p_lemon__ListDigraph g, SWIGTYPE_p_lemon__ListDigraph__NodeMapT_nodeData_t nData) {
    return new SWIGTYPE_p_std__string(activity_networkJNI.writeNodeData(SWIGTYPE_p_lemon__ListDigraph.getCPtr(g), SWIGTYPE_p_lemon__ListDigraph__NodeMapT_nodeData_t.getCPtr(nData)), true);
  }

  public static void outputNodeData(SWIGTYPE_p_lemon__ListDigraph g, SWIGTYPE_p_lemon__ListDigraph__NodeMapT_nodeData_t nData, int fileId) {
    activity_networkJNI.outputNodeData(SWIGTYPE_p_lemon__ListDigraph.getCPtr(g), SWIGTYPE_p_lemon__ListDigraph__NodeMapT_nodeData_t.getCPtr(nData), fileId);
  }

  public static void displayNodeData(SWIGTYPE_p_lemon__ListDigraph g, SWIGTYPE_p_lemon__ListDigraph__NodeMapT_nodeData_t nData) {
    activity_networkJNI.displayNodeData__SWIG_0(SWIGTYPE_p_lemon__ListDigraph.getCPtr(g), SWIGTYPE_p_lemon__ListDigraph__NodeMapT_nodeData_t.getCPtr(nData));
  }

  public static void displayNodeData(SWIGTYPE_p_lemon__ListDigraph g, SWIGTYPE_p_lemon__ListDigraph__NodeMapT_int_t label) {
    activity_networkJNI.displayNodeData__SWIG_1(SWIGTYPE_p_lemon__ListDigraph.getCPtr(g), SWIGTYPE_p_lemon__ListDigraph__NodeMapT_int_t.getCPtr(label));
  }

  public static void displayNodeData(SWIGTYPE_p_lemon__ListDigraph g, SWIGTYPE_p_lemon__ListDigraph__NodeMapT_bool_t label) {
    activity_networkJNI.displayNodeData__SWIG_2(SWIGTYPE_p_lemon__ListDigraph.getCPtr(g), SWIGTYPE_p_lemon__ListDigraph__NodeMapT_bool_t.getCPtr(label));
  }

  public static void displayNodeData(SWIGTYPE_p_lemon__ListDigraph g, SWIGTYPE_p_lemon__ListDigraph__NodeMapT_double_t label) {
    activity_networkJNI.displayNodeData__SWIG_3(SWIGTYPE_p_lemon__ListDigraph.getCPtr(g), SWIGTYPE_p_lemon__ListDigraph__NodeMapT_double_t.getCPtr(label));
  }

  public static void digraphCopy(SWIGTYPE_p_lemon__ListDigraph original, SWIGTYPE_p_lemon__ListDigraph__ArcMapT_arcData_t origArcMap, SWIGTYPE_p_lemon__ListDigraph__NodeMapT_nodeData_t origNodeMap, SWIGTYPE_p_lemon__ListDigraph copy, SWIGTYPE_p_lemon__ListDigraph__ArcMapT_arcData_t copyArcMap, SWIGTYPE_p_lemon__ListDigraph__NodeMapT_nodeData_t copyNodeMap) {
    activity_networkJNI.digraphCopy(SWIGTYPE_p_lemon__ListDigraph.getCPtr(original), SWIGTYPE_p_lemon__ListDigraph__ArcMapT_arcData_t.getCPtr(origArcMap), SWIGTYPE_p_lemon__ListDigraph__NodeMapT_nodeData_t.getCPtr(origNodeMap), SWIGTYPE_p_lemon__ListDigraph.getCPtr(copy), SWIGTYPE_p_lemon__ListDigraph__ArcMapT_arcData_t.getCPtr(copyArcMap), SWIGTYPE_p_lemon__ListDigraph__NodeMapT_nodeData_t.getCPtr(copyNodeMap));
  }

  public static void reverseArcs(SWIGTYPE_p_lemon__ListDigraph g) {
    activity_networkJNI.reverseArcs(SWIGTYPE_p_lemon__ListDigraph.getCPtr(g));
  }

  public static SWIGTYPE_p_std__string IntToString(int number) {
    return new SWIGTYPE_p_std__string(activity_networkJNI.IntToString(number), true);
  }

  public static void armArrayToCpp(SWIGTYPE_p_arma__MatT_double_t in, SWIGTYPE_p_double out) {
    activity_networkJNI.armArrayToCpp(SWIGTYPE_p_arma__MatT_double_t.getCPtr(in), SWIGTYPE_p_double.getCPtr(out));
  }

  public static boolean printSolution(SWIGTYPE_p_ClpSimplex model) {
    return activity_networkJNI.printSolution(SWIGTYPE_p_ClpSimplex.getCPtr(model));
  }

  public static double randTriangular(double min, double mode, double max) {
    return activity_networkJNI.randTriangular(min, mode, max);
  }

  public static void replaceAll(SWIGTYPE_p_std__string str, SWIGTYPE_p_std__string from, SWIGTYPE_p_std__string to) {
    activity_networkJNI.replaceAll(SWIGTYPE_p_std__string.getCPtr(str), SWIGTYPE_p_std__string.getCPtr(from), SWIGTYPE_p_std__string.getCPtr(to));
  }

}
