/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.morgan.opnet.swig.activitynet;

public class ActivityNetwork {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ActivityNetwork(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ActivityNetwork obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        activity_networkJNI.delete_ActivityNetwork(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ActivityNetwork() {
    this(activity_networkJNI.new_ActivityNetwork__SWIG_0(), true);
  }

  public ActivityNetwork(SWIGTYPE_p_std__string inputFile) {
    this(activity_networkJNI.new_ActivityNetwork__SWIG_1(SWIGTYPE_p_std__string.getCPtr(inputFile)), true);
  }

  public void setInputFile(SWIGTYPE_p_std__string inputFile) {
    activity_networkJNI.ActivityNetwork_setInputFile(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(inputFile));
  }

  public void setDurations(SWIGTYPE_p_std__mapT_int_double_t durations) {
    activity_networkJNI.ActivityNetwork_setDurations(swigCPtr, this, SWIGTYPE_p_std__mapT_int_double_t.getCPtr(durations));
  }

  public boolean readGPR_cons() {
    return activity_networkJNI.ActivityNetwork_readGPR_cons__SWIG_0(swigCPtr, this);
  }

  public boolean readGPR_cons(SWIGTYPE_p_std__string fileName) {
    return activity_networkJNI.ActivityNetwork_readGPR_cons__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(fileName));
  }

  public boolean readGPR_bounds() {
    return activity_networkJNI.ActivityNetwork_readGPR_bounds__SWIG_0(swigCPtr, this);
  }

  public boolean readGPR_bounds(SWIGTYPE_p_std__string fileName) {
    return activity_networkJNI.ActivityNetwork_readGPR_bounds__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(fileName));
  }

  public boolean readGPR_beta() {
    return activity_networkJNI.ActivityNetwork_readGPR_beta__SWIG_0(swigCPtr, this);
  }

  public boolean readGPR_beta(SWIGTYPE_p_std__string fileName) {
    return activity_networkJNI.ActivityNetwork_readGPR_beta__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(fileName));
  }

  public void readGPR_all() {
    activity_networkJNI.ActivityNetwork_readGPR_all(swigCPtr, this);
  }

  public void clearEarlyAndLateStarts(SWIGTYPE_p_lemon__ListDigraph g, SWIGTYPE_p_lemon__ListDigraph__NodeMapT_nodeData_t nData) {
    activity_networkJNI.ActivityNetwork_clearEarlyAndLateStarts(swigCPtr, this, SWIGTYPE_p_lemon__ListDigraph.getCPtr(g), SWIGTYPE_p_lemon__ListDigraph__NodeMapT_nodeData_t.getCPtr(nData));
  }

  public void clearArcMap(SWIGTYPE_p_lemon__ListDigraph__ArcMapT_double_t map) {
    activity_networkJNI.ActivityNetwork_clearArcMap__SWIG_0(swigCPtr, this, SWIGTYPE_p_lemon__ListDigraph__ArcMapT_double_t.getCPtr(map));
  }

  public void clearArcMap(SWIGTYPE_p_lemon__ListDigraph__ArcMapT_int_t map) {
    activity_networkJNI.ActivityNetwork_clearArcMap__SWIG_1(swigCPtr, this, SWIGTYPE_p_lemon__ListDigraph__ArcMapT_int_t.getCPtr(map));
  }

  public void clearArcMap(SWIGTYPE_p_lemon__ListDigraph__ArcMapT_bool_t map) {
    activity_networkJNI.ActivityNetwork_clearArcMap__SWIG_2(swigCPtr, this, SWIGTYPE_p_lemon__ListDigraph__ArcMapT_bool_t.getCPtr(map));
  }

  public void clearNodeMap(SWIGTYPE_p_lemon__ListDigraph__NodeMapT_double_t map) {
    activity_networkJNI.ActivityNetwork_clearNodeMap__SWIG_0(swigCPtr, this, SWIGTYPE_p_lemon__ListDigraph__NodeMapT_double_t.getCPtr(map));
  }

  public void clearNodeMap(SWIGTYPE_p_lemon__ListDigraph__NodeMapT_int_t map) {
    activity_networkJNI.ActivityNetwork_clearNodeMap__SWIG_1(swigCPtr, this, SWIGTYPE_p_lemon__ListDigraph__NodeMapT_int_t.getCPtr(map));
  }

  public void clearNodeMap(SWIGTYPE_p_lemon__ListDigraph__NodeMapT_bool_t map) {
    activity_networkJNI.ActivityNetwork_clearNodeMap__SWIG_2(swigCPtr, this, SWIGTYPE_p_lemon__ListDigraph__NodeMapT_bool_t.getCPtr(map));
  }

  public void displayCriticalSubgraph(SWIGTYPE_p_lemon__ListDigraph g, SWIGTYPE_p_lemon__ListDigraph__ArcMapT_arcData_t aData) {
    activity_networkJNI.ActivityNetwork_displayCriticalSubgraph(swigCPtr, this, SWIGTYPE_p_lemon__ListDigraph.getCPtr(g), SWIGTYPE_p_lemon__ListDigraph__ArcMapT_arcData_t.getCPtr(aData));
  }

  public SWIGTYPE_p_std__string writeCriticalSubgraph(SWIGTYPE_p_lemon__ListDigraph g, SWIGTYPE_p_lemon__ListDigraph__ArcMapT_arcData_t aData) {
    return new SWIGTYPE_p_std__string(activity_networkJNI.ActivityNetwork_writeCriticalSubgraph(swigCPtr, this, SWIGTYPE_p_lemon__ListDigraph.getCPtr(g), SWIGTYPE_p_lemon__ListDigraph__ArcMapT_arcData_t.getCPtr(aData)), true);
  }

  public void runGPR_TCTO_Flow(String inFile, String outFile) {
    activity_networkJNI.ActivityNetwork_runGPR_TCTO_Flow(swigCPtr, this, inFile, outFile);
  }

  public void runGPR_TCTO_LP(int outputFileId) {
    activity_networkJNI.ActivityNetwork_runGPR_TCTO_LP__SWIG_0(swigCPtr, this, outputFileId);
  }

  public boolean runGPR_TCTO_LP(int dueDate, SWIGTYPE_p_ClpSimplex model) {
    return activity_networkJNI.ActivityNetwork_runGPR_TCTO_LP__SWIG_1(swigCPtr, this, dueDate, SWIGTYPE_p_ClpSimplex.getCPtr(model));
  }

  public void runMinExpectedCost() {
    activity_networkJNI.ActivityNetwork_runMinExpectedCost(swigCPtr, this);
  }

  public boolean writeSolution(SWIGTYPE_p_ClpSimplex model, int dueDate, String outputFileName, boolean append) {
    return activity_networkJNI.ActivityNetwork_writeSolution(swigCPtr, this, SWIGTYPE_p_ClpSimplex.getCPtr(model), dueDate, outputFileName, append);
  }

  public void displayGraphData() {
    activity_networkJNI.ActivityNetwork_displayGraphData(swigCPtr, this);
  }

  public boolean isCritical(int activity) {
    return activity_networkJNI.ActivityNetwork_isCritical(swigCPtr, this, activity);
  }

  public double duration(int activity) {
    return activity_networkJNI.ActivityNetwork_duration(swigCPtr, this, activity);
  }

  public int totalFloat(int activity) {
    return activity_networkJNI.ActivityNetwork_totalFloat(swigCPtr, this, activity);
  }

  public int earlyStart(int node) {
    return activity_networkJNI.ActivityNetwork_earlyStart(swigCPtr, this, node);
  }

  public int lateStart(int node) {
    return activity_networkJNI.ActivityNetwork_lateStart(swigCPtr, this, node);
  }

  public SWIGTYPE_p_lemon__ListDigraph getNetwork() {
    return new SWIGTYPE_p_lemon__ListDigraph(activity_networkJNI.ActivityNetwork_getNetwork(swigCPtr, this), false);
  }

  public SWIGTYPE_p_std__mapT_int_double_t getDurations() {
    return new SWIGTYPE_p_std__mapT_int_double_t(activity_networkJNI.ActivityNetwork_getDurations(swigCPtr, this), false);
  }

  public SWIGTYPE_p_std__mapT_int_bool_t getCritical() {
    return new SWIGTYPE_p_std__mapT_int_bool_t(activity_networkJNI.ActivityNetwork_getCritical(swigCPtr, this), false);
  }

  public SWIGTYPE_p_std__mapT_int_int_t getEarlyStart() {
    return new SWIGTYPE_p_std__mapT_int_int_t(activity_networkJNI.ActivityNetwork_getEarlyStart(swigCPtr, this), false);
  }

  public SWIGTYPE_p_std__mapT_int_int_t getLateStart() {
    return new SWIGTYPE_p_std__mapT_int_int_t(activity_networkJNI.ActivityNetwork_getLateStart(swigCPtr, this), false);
  }

  public int getMakespan() {
    return activity_networkJNI.ActivityNetwork_getMakespan(swigCPtr, this);
  }

  public boolean isNetworkEmpty() {
    return activity_networkJNI.ActivityNetwork_isNetworkEmpty(swigCPtr, this);
  }

  public SWIGTYPE_p_std__mapT_int_int_t getTotalFloat() {
    return new SWIGTYPE_p_std__mapT_int_int_t(activity_networkJNI.ActivityNetwork_getTotalFloat(swigCPtr, this), false);
  }

  public void setWriteToFile(boolean writeToFile) {
    activity_networkJNI.ActivityNetwork_setWriteToFile(swigCPtr, this, writeToFile);
  }

  public boolean isWriteToFile() {
    return activity_networkJNI.ActivityNetwork_isWriteToFile(swigCPtr, this);
  }

}
