/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.morgan.opnet.swig.activitynet;

public final class ActivityType {
  public final static ActivityType REG = new ActivityType("REG");
  public final static ActivityType DUMMY = new ActivityType("DUMMY");
  public final static ActivityType GPR = new ActivityType("GPR");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ActivityType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ActivityType.class + " with value " + swigValue);
  }

  private ActivityType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ActivityType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ActivityType(String swigName, ActivityType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ActivityType[] swigValues = { REG, DUMMY, GPR };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

