/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.morgan.opnet.swig.activitynet;

public final class GPRType {
  public final static GPRType FS = new GPRType("FS");
  public final static GPRType FF = new GPRType("FF");
  public final static GPRType SS = new GPRType("SS");
  public final static GPRType SF = new GPRType("SF");
  public final static GPRType NA = new GPRType("NA");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GPRType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GPRType.class + " with value " + swigValue);
  }

  private GPRType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GPRType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GPRType(String swigName, GPRType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GPRType[] swigValues = { FS, FF, SS, SF, NA };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

