/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.morgan.opnet.swig.activitynet;

public class nodeData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected nodeData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nodeData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        activity_networkJNI.delete_nodeData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(int value) {
    activity_networkJNI.nodeData_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return activity_networkJNI.nodeData_id_get(swigCPtr, this);
  }

  public void setName(SWIGTYPE_p_std__string value) {
    activity_networkJNI.nodeData_name_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public SWIGTYPE_p_std__string getName() {
    return new SWIGTYPE_p_std__string(activity_networkJNI.nodeData_name_get(swigCPtr, this), true);
  }

  public void setEarlyStart(double value) {
    activity_networkJNI.nodeData_earlyStart_set(swigCPtr, this, value);
  }

  public double getEarlyStart() {
    return activity_networkJNI.nodeData_earlyStart_get(swigCPtr, this);
  }

  public void setLateStart(double value) {
    activity_networkJNI.nodeData_lateStart_set(swigCPtr, this, value);
  }

  public double getLateStart() {
    return activity_networkJNI.nodeData_lateStart_get(swigCPtr, this);
  }

  public void setNodeSlack(double value) {
    activity_networkJNI.nodeData_nodeSlack_set(swigCPtr, this, value);
  }

  public double getNodeSlack() {
    return activity_networkJNI.nodeData_nodeSlack_get(swigCPtr, this);
  }

  public nodeData() {
    this(activity_networkJNI.new_nodeData(), true);
  }

}
